# -*- coding: utf-8 -*-
"""Copia de Untitled80.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U28I8KRiurgFt9qw5J_iPot3nBZoUwTW
"""

!pip install discord

!unzip ./converted_keras.zip

# importamos la libreria PIL: Python Imaging Library
# es necesario para poder abrir la imagen a analizar
import PIL
from PIL import Image, ImageOps
import numpy as np
# Instalamos keras, libreria necesaria para que funcionen
# las redes neuronales
!pip install -q tf-keras==2.19.0 h5py==3.11.0
# Importando tf-keras – una versión de Keras compatible con modelos .h5
import tf_keras as keras
# Importando la función load_model de tf_keras, que nos
# permitira cargar el modelo de google teachable machine
from tf_keras.models import load_model

import discord
from discord.ext import commands
import nest_asyncio

nest_asyncio.apply()

model_path = "./keras_model.h5"
labels_path = "./labels.txt"

def get_class(image_path):
  np.set_printoptions(suppress=True)
  model = load_model(model_path, compile=False)
  class_names = open(labels_path, "r").readlines()
  data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)
  image = Image.open(image_path).convert("RGB")
  size = (224, 224)
  image = ImageOps.fit(image, size, Image.Resampling.LANCZOS)
  image_array = np.asarray(image)
  normalized_image_array = (image_array.astype(np.float32) / 127.5) - 1
  data[0] = normalized_image_array
  prediction = model.predict(data)
  print(prediction)
  index = np.argmax(prediction)
  class_name = class_names[index]
  confidence_score = prediction[0][index]
  text1 = f"Clase: {class_name[2:]} Probabilidad: {confidence_score}"
  return text1

#Definimos los permisos del bot
intents = discord.Intents.default()
intents.message_content = True
#creamos el bot
bot = commands.Bot(command_prefix='$', intents=intents)

@bot.event
async def on_ready():
    print(f'Inicie cesion como {bot.user}')
#este comando saluda al usuario
#para activarlo se escribe $hello
@bot.command()
async def hello(ctx):
    await ctx.send(f'Hola! soy el {bot.user}!')

#escribe tu codigo aqui
@bot.command()
async def check(ctx):
  if ctx.message.attachments:
    for archivo in ctx.message.attachments:
      file_name = archivo.filename
      file_url = archivo.url
      await archivo.save(f"./{file_name}")
      await ctx.send("Imagen guardada con exito.")
      respuesta = get_class(f"./{file_name}")
      await ctx.send(respuesta)
  else:
    await ctx.send("No has enviado ninguna imagen")


bot.run("MTU0MDE0NDE2OTc5ODk5NTk4OA.GqBELJ.AEX5I8xKCugsMndBacK_QbCFWnML-nVnGHPtmg")

